name: flutter_ecommerce_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.0
  flutter_bloc: ^8.1.6
  flutter_carousel_widget: ^2.3.0
  flutter_dash: ^1.0.0
  flutter_facebook_auth: ^7.0.1
  flutter_native_splash: ^2.4.1
  google_sign_in: ^6.2.1
  persistent_bottom_nav_bar_v2: ^5.3.0
  dio: ^5.8.0+1
  flutter_otp_text_field: ^1.1.3+2
#  image_picker: ^1.0.4
#  permission_handler: ^10.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_native_splash:
  color: "#673AB7"
  #background_image: "assets/background.png"
  image: assets/images/splash.png

  android_12:
    color: "#673AB7"
    image: assets/images/splash.png
           assets/images/facebook_logo.png
           assets/images/google_logo.png
