name: flutter_ecommerce_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.0
  flutter_bloc: ^9.1.0
  flutter_carousel_widget: ^2.3.0
  flutter_dash: ^1.0.0
  flutter_facebook_auth: ^7.0.1
  flutter_native_splash: ^2.4.1
  google_sign_in: ^6.2.1
  persistent_bottom_nav_bar_v2: ^5.3.0
  dio: ^5.8.0+1
  flutter_otp_text_field: ^1.1.3+2
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  internet_connection_checker_plus: ^2.7.2
  bloc: ^9.0.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  carousel_slider: ^5.0.0
  timeline_tile: ^2.0.0
  material_symbols_icons: ^4.2815.0
  flutter_screenutil: ^5.9.3
  intl: ^0.19.0
  country_code_picker: ^3.3.0
  image_picker: ^1.0.2
  permission_handler: ^10.2.0





dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  freezed: ^3.0.6


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/translations/


  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Italic.ttf
          style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
